spring:
  main:
    banner-mode: off
  thymeleaf:
    cache: false
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3308/serv_launch?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

mybatis-plus:
  type-aliases-package: org.soft.launch.modules.sys.entity
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    banner: off
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl